# Generated by Django 5.1.4 on 2025-01-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_genderdistribution_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
