# Generated by Django 5.1.4 on 2025-01-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='coursework1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='module',
            name='coursework2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='module',
            name='coursework3',
            field=models.FloatField(default=0.0),
        ),
    ]
